#!/bin/ash
set -e

readonly SOCK_FILE="/run/app/php-fpm.sock"
readonly PID_FILE="/run/app/php-fpm.pid"
readonly FPM_EXE=/usr/sbin/php-fpm$PHP_VERS

[[ -e "$SOCK_FILE" ]] && rm -v "$SOCK_FILE"
[[ -e "$PID_FILE" ]] && rm -v "$PID_FILE"
touch "$APP_LOGDIR"/php.log

exec $FPM_EXE --nodaemonize --fpm-config "$APP_PHP_CONF_DIR"/php-fpm.conf --pid "$PID_FILE"

# vim: set ft=bash ts=2 sts=2 expandtab:
