#!/bin/sh

if [ -x /usr/bin/php81 ]; then
  _exe=/usr/bin/php82
elif [ -x /usr/bin/php82 ]; then
  _exe=/usr/bin/php82
elif [ -x /usr/bin/php83 ]; then
  _exe=/usr/bin/php83
else
  echo "Could not find valid php installation!" >&2
  exit 1
fi

$_exe -f /usr/share/webapps/nextcloud/cron.php
